version: '3.8'

services:
  backend:
    build:
      context: ./src/weather_app/backend
      dockerfile: Dockerfile
    container_name: weather-backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - PYTHONPATH=/app
    volumes:
      - ./src/weather_app/backend:/app/weather_app/backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - weather-app-network

  frontend:
    build:
      context: ./src/weather_app/frontend
      dockerfile: Dockerfile
    container_name: weather-frontend
    ports:
      - "8501:8501"
    environment:
      - PORT=8501
      - BACKEND_URL=http://weather-backend:8000
      - PYTHONPATH=/app
    volumes:
      - ./src/weather_app/frontend:/app/weather_app/frontend
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - weather-app-network

networks:
  weather-app-network:
    driver: bridge
