project_id     = "load-balancing-experiment"
region         = "us-central1"
frontend_image = "us-central1-docker.pkg.dev/load-balancing-experiment/weather-app-frontend:latest"
backend_image  = "us-central1-docker.pkg.dev/load-balancing-experiment/weather-app-backend:latest"
domain_name    = "sdfingfd.xyz"
admin_email    = "okeefe.niemann@gmail.com" 